# Generated by Django 2.2.10 on 2021-10-13 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='вопрос')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Ответ текстом'), (2, 'Ответ с выбором одного варианта'), (3, 'Ответ с выбором нескольких вариантов')], verbose_name='Тип ответа')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
        migrations.AlterField(
            model_name='pool',
            name='description',
            field=models.CharField(max_length=200, verbose_name='описание'),
        ),
        migrations.CreateModel(
            name='TextResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
            options={
                'verbose_name': 'текстовые ответы',
                'verbose_name_plural': 'текстовые ответы',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Pool'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='вариант ответа')),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
            options={
                'verbose_name': 'варианты ответов',
                'verbose_name_plural': 'варианты ответов',
            },
        ),
    ]
