# Generated by Django 2.2.10 on 2021-10-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20211015_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='вариант ответа'),
        ),
        migrations.DeleteModel(
            name='TextResponse',
        ),
    ]
