# Generated by Django 2.2.10 on 2021-10-19 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0006_auto_20211019_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pool',
            new_name='poll',
        ),
        migrations.RenameModel(
            old_name='Pool',
            new_name='Poll',
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean_response', models.BooleanField(blank=True, null=True, verbose_name='ответ на вариант')),
                ('text_response', models.TextField(blank=True, null=True, verbose_name='текстовый ответ')),
                ('choice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Choice')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ответ',
                'verbose_name_plural': 'ответы',
            },
        ),
    ]
