# Generated by Django 2.2.10 on 2021-10-20 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20211019_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='polls.Poll'),
        ),
    ]
